[project]
name = "remote-denoiser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "python-multipart>=0.0.21",
    "rawforge>=0.0.1",
    "rawrefinery>=1.3.4",
    "uvicorn>=0.40.0",
]
